name: Build & Deploy (OVH FTP)

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [rebuild-site]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install sync deps
        run: npm i node-fetch@3 critical postcss postcss-cli autoprefixer @fullhuman/postcss-purgecss jquery popper.js

      - name: Sync Strapi → Hugo (blog articles)
        run: node tools/strapi-to-hugo.mjs --type=articles

      - name: Sync Strapi → Hugo (portfolio projects)
        run: node tools/strapi-to-hugo.mjs --type=projects

      - name: Sync Strapi → Hugo (portfolio projects)
        run: node tools/strapi-to-hugo.mjs --type=testimonials

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.128.2"
          extended: true

      - name: Build site & Generate Critical CSS
        run: |
          hugo --minify
          node tools/generate-critical.mjs

      - name: Deploy to OVH (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./public/
          server-dir: ./pixicode/
          delete: true
